# Generated by Django 3.2.15 on 2026-05-22 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_screenplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, verbose_name='定义键')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('source_system', models.CharField(default='linknow', max_length=50, verbose_name='来源系统')),
                ('graph_schema', models.JSONField(blank=True, default=dict, verbose_name='图定义')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_definitions', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '工作流定义',
                'verbose_name_plural': '工作流定义',
                'db_table': 'workflow_definitions',
                'ordering': ['key', '-version'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待运行'), ('running', '运行中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('trigger_mode', models.CharField(choices=[('manual', '手动'), ('api', 'API'), ('callback', '回调'), ('retry', '重试')], default='api', max_length=20, verbose_name='触发方式')),
                ('external_run_id', models.CharField(blank=True, default='', max_length=255, verbose_name='外部运行ID')),
                ('current_node_key', models.CharField(blank=True, default='', max_length=100, verbose_name='当前节点键')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='上下文数据')),
                ('final_output', models.JSONField(blank=True, default=dict, verbose_name='最终输出')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='workflows.workflowdefinition', verbose_name='工作流定义')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='projects.project', verbose_name='项目')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='projects.series', verbose_name='作品')),
            ],
            options={
                'verbose_name': '工作流运行',
                'verbose_name_plural': '工作流运行',
                'db_table': 'workflow_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNodeRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_key', models.CharField(max_length=100, verbose_name='节点键')),
                ('node_type', models.CharField(max_length=50, verbose_name='节点类型')),
                ('status', models.CharField(choices=[('pending', '待运行'), ('running', '运行中'), ('waiting_callback', '等待回调'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='序号')),
                ('external_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='外部任务ID')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255, verbose_name='幂等键')),
                ('input_payload', models.JSONField(blank=True, default=dict, verbose_name='输入')),
                ('output_payload', models.JSONField(blank=True, default=dict, verbose_name='输出')),
                ('normalized_output', models.JSONField(blank=True, default=dict, verbose_name='标准化输出')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='workflows.workflowrun', verbose_name='工作流运行')),
            ],
            options={
                'verbose_name': '工作流节点运行',
                'verbose_name_plural': '工作流节点运行',
                'db_table': 'workflow_node_runs',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowCallbackEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=100, verbose_name='提供方')),
                ('event_type', models.CharField(max_length=100, verbose_name='事件类型')),
                ('idempotency_key', models.CharField(max_length=255, unique=True, verbose_name='幂等键')),
                ('external_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='外部任务ID')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='回调数据')),
                ('process_status', models.CharField(choices=[('received', '已接收'), ('processed', '已处理'), ('ignored', '已忽略'), ('failed', '失败')], default='received', max_length=20, verbose_name='处理状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('node_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_events', to='workflows.workflownoderun', verbose_name='节点运行')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_events', to='workflows.workflowrun', verbose_name='工作流运行')),
            ],
            options={
                'verbose_name': '工作流回调事件',
                'verbose_name_plural': '工作流回调事件',
                'db_table': 'workflow_callback_events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('binding_type', models.CharField(choices=[('project', '项目'), ('stage', '阶段'), ('storyboard', '分镜'), ('image', '图片'), ('camera', '运镜'), ('video', '视频')], max_length=20, verbose_name='绑定类型')),
                ('target_id', models.CharField(max_length=64, verbose_name='目标ID')),
                ('target_key', models.CharField(blank=True, default='', max_length=255, verbose_name='目标键')),
                ('sequence_number', models.IntegerField(blank=True, null=True, verbose_name='分镜序号')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('node_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='workflows.workflownoderun', verbose_name='节点运行')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='workflows.workflowrun', verbose_name='工作流运行')),
            ],
            options={
                'verbose_name': '工作流绑定',
                'verbose_name_plural': '工作流绑定',
                'db_table': 'workflow_bindings',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['project', 'status'], name='wf_run_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['external_run_id'], name='wf_run_external_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownoderun',
            index=models.Index(fields=['workflow_run', 'status'], name='wf_node_run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownoderun',
            index=models.Index(fields=['external_task_id'], name='wf_node_external_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownoderun',
            index=models.Index(fields=['idempotency_key'], name='wf_node_idempotency_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflownoderun',
            constraint=models.UniqueConstraint(fields=('workflow_run', 'node_key', 'sequence'), name='uniq_workflow_run_node_sequence'),
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['source_system', 'is_active'], name='workflow_def_source_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowdefinition',
            constraint=models.UniqueConstraint(fields=('key', 'version'), name='uniq_workflow_definition_key_version'),
        ),
        migrations.AddIndex(
            model_name='workflowcallbackevent',
            index=models.Index(fields=['workflow_run', 'provider'], name='wf_cb_run_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowcallbackevent',
            index=models.Index(fields=['external_task_id'], name='wf_cb_external_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowbinding',
            index=models.Index(fields=['workflow_run', 'binding_type'], name='wf_binding_run_type_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowbinding',
            index=models.Index(fields=['target_id'], name='wf_binding_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('node_run__isnull', False)), fields=('node_run', 'binding_type', 'target_key'), name='uniq_workflow_binding_node_type_target_key'),
        ),
    ]
