# Generated by Django 3.2.15 on 2026-05-22 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_screenplay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowCanvas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='画板名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='画板描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '激活'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('external_canvas_id', models.CharField(blank=True, default='', max_length=255, verbose_name='外部画板ID')),
                ('graph_metadata', models.JSONField(blank=True, default=dict, verbose_name='画板元数据')),
                ('viewport', models.JSONField(blank=True, default=dict, verbose_name='视口信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工作流画板',
                'verbose_name_plural': '工作流画板',
                'db_table': 'workflow_canvases',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_key', models.CharField(max_length=100, verbose_name='连线键')),
                ('source_handle', models.CharField(blank=True, default='', max_length=100, verbose_name='源锚点')),
                ('target_handle', models.CharField(blank=True, default='', max_length=100, verbose_name='目标锚点')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='连线元数据')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工作流连线',
                'verbose_name_plural': '工作流连线',
                'db_table': 'workflow_edges',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_key', models.CharField(max_length=100, verbose_name='节点键')),
                ('node_type', models.CharField(max_length=50, verbose_name='节点类型')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='节点标题')),
                ('status', models.CharField(choices=[('idle', '空闲'), ('dirty', '待执行'), ('queued', '已排队'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('stale', '结果过期')], default='idle', max_length=20, verbose_name='节点状态')),
                ('position_x', models.FloatField(default=0, verbose_name='横坐标')),
                ('position_y', models.FloatField(default=0, verbose_name='纵坐标')),
                ('width', models.IntegerField(default=320, verbose_name='宽度')),
                ('height', models.IntegerField(default=180, verbose_name='高度')),
                ('config_data', models.JSONField(blank=True, default=dict, verbose_name='节点配置')),
                ('input_mapping', models.JSONField(blank=True, default=dict, verbose_name='输入映射')),
                ('output_schema', models.JSONField(blank=True, default=dict, verbose_name='输出结构')),
                ('latest_output', models.JSONField(blank=True, default=dict, verbose_name='最近一次输出')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='最近执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工作流节点',
                'verbose_name_plural': '工作流节点',
                'db_table': 'workflow_nodes',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='workflownoderun',
            name='trigger_source',
            field=models.CharField(blank=True, default='manual', max_length=50, verbose_name='触发来源'),
        ),
        migrations.AddField(
            model_name='workflownoderun',
            name='upstream_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='上游快照'),
        ),
        migrations.AlterField(
            model_name='workflowbinding',
            name='workflow_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='workflows.workflowrun', verbose_name='工作流运行'),
        ),
        migrations.AlterField(
            model_name='workflowcallbackevent',
            name='workflow_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callback_events', to='workflows.workflowrun', verbose_name='工作流运行'),
        ),
        migrations.AlterField(
            model_name='workflownoderun',
            name='workflow_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='workflows.workflowrun', verbose_name='工作流运行'),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.workflowcanvas', verbose_name='画板'),
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='workflows.workflowcanvas', verbose_name='画板'),
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='source_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='workflows.workflownode', verbose_name='源节点'),
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='target_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='workflows.workflownode', verbose_name='目标节点'),
        ),
        migrations.AddField(
            model_name='workflowcanvas',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_canvases', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='workflowcanvas',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canvases', to='workflows.workflowdefinition', verbose_name='工作流模板'),
        ),
        migrations.AddField(
            model_name='workflowcanvas',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_canvases', to='projects.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='workflowcanvas',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_canvases', to='projects.series', verbose_name='作品'),
        ),
        migrations.AddField(
            model_name='workflowbinding',
            name='canvas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='workflows.workflowcanvas', verbose_name='画板'),
        ),
        migrations.AddField(
            model_name='workflowbinding',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bindings', to='workflows.workflownode', verbose_name='节点'),
        ),
        migrations.AddField(
            model_name='workflowcallbackevent',
            name='canvas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callback_events', to='workflows.workflowcanvas', verbose_name='画板'),
        ),
        migrations.AddField(
            model_name='workflownoderun',
            name='canvas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='workflows.workflowcanvas', verbose_name='画板'),
        ),
        migrations.AddField(
            model_name='workflownoderun',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='workflows.workflownode', verbose_name='节点'),
        ),
        migrations.AddIndex(
            model_name='workflowbinding',
            index=models.Index(fields=['canvas', 'binding_type'], name='wf_binding_canvas_type_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowcallbackevent',
            index=models.Index(fields=['canvas', 'provider'], name='wf_cb_canvas_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownoderun',
            index=models.Index(fields=['canvas', 'status'], name='wf_node_canvas_run_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflownoderun',
            constraint=models.UniqueConstraint(condition=models.Q(('canvas__isnull', False), ('node__isnull', False)), fields=('canvas', 'node', 'sequence'), name='uniq_wf_canvas_node_sequence'),
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['canvas', 'status'], name='wf_node_canvas_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflownode',
            constraint=models.UniqueConstraint(fields=('canvas', 'node_key'), name='uniq_wf_canvas_node_key'),
        ),
        migrations.AddIndex(
            model_name='workflowedge',
            index=models.Index(fields=['canvas', 'is_enabled'], name='wf_edge_canvas_enabled_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowedge',
            constraint=models.UniqueConstraint(fields=('canvas', 'edge_key'), name='uniq_wf_canvas_edge_key'),
        ),
        migrations.AddIndex(
            model_name='workflowcanvas',
            index=models.Index(fields=['project', 'status'], name='wf_canvas_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowcanvas',
            index=models.Index(fields=['external_canvas_id'], name='wf_canvas_external_idx'),
        ),
    ]
