# Generated by Django 3.2.15 on 2026-06-02 05:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_auto_20260522_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='status',
            field=models.CharField(choices=[('idle', '空闲'), ('dirty', '待执行'), ('blocked', '已阻断'), ('queued', '已排队'), ('running', '运行中'), ('waiting_callback', '等待回调'), ('completed', '已完成'), ('failed', '失败'), ('stale', '结果过期'), ('cancelled', '已取消')], default='idle', max_length=20, verbose_name='节点状态'),
        ),
        migrations.AlterField(
            model_name='workflownoderun',
            name='status',
            field=models.CharField(choices=[('pending', '待运行'), ('blocked', '已阻断'), ('queued', '已排队'), ('running', '运行中'), ('waiting_callback', '等待回调'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='WorkflowNodeRunEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100, verbose_name='事件类型')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='事件载荷')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('canvas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_run_events', to='workflows.workflowcanvas', verbose_name='画板')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_events', to='workflows.workflownode', verbose_name='节点')),
                ('node_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workflows.workflownoderun', verbose_name='节点运行')),
                ('workflow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_run_events', to='workflows.workflowrun', verbose_name='工作流运行')),
            ],
            options={
                'verbose_name': '节点运行事件',
                'verbose_name_plural': '节点运行事件',
                'db_table': 'workflow_node_run_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflownoderunevent',
            index=models.Index(fields=['node_run', 'created_at'], name='wf_node_run_event_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownoderunevent',
            index=models.Index(fields=['workflow_run', 'created_at'], name='wf_run_event_created_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownoderunevent',
            index=models.Index(fields=['canvas', 'created_at'], name='wf_canvas_event_created_idx'),
        ),
    ]
