# Generated by Django 3.2.15 on 2026-06-02 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_auto_20260602_1343'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowNodeSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='结构键')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('node_family', models.CharField(choices=[('scalar_text', '单值文本'), ('collection_text', '集合文本'), ('media', '媒体'), ('custom', '自定义')], default='collection_text', max_length=50, verbose_name='节点家族')),
                ('workflow_node_type', models.CharField(max_length=100, verbose_name='工作流节点类型')),
                ('stage_type', models.CharField(blank=True, default='', max_length=50, verbose_name='阶段类型')),
                ('schema_config', models.JSONField(blank=True, default=dict, verbose_name='结构配置')),
                ('ui_config', models.JSONField(blank=True, default=dict, verbose_name='界面配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_node_schemas', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '节点结构定义',
                'verbose_name_plural': '节点结构定义',
                'db_table': 'workflow_node_schemas',
                'ordering': ['key'],
            },
        ),
        migrations.AddIndex(
            model_name='workflownodeschema',
            index=models.Index(fields=['workflow_node_type', 'is_active'], name='wf_schema_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownodeschema',
            index=models.Index(fields=['node_family', 'is_active'], name='wf_schema_family_active_idx'),
        ),
    ]
