# Generated by Django 3.2.15 on 2026-06-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_workflownodeschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownodeschema',
            name='system_prompt',
            field=models.TextField(blank=True, default='', verbose_name='系统提示词'),
        ),
        migrations.RemoveIndex(
            model_name='workflownodeschema',
            name='wf_schema_type_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflownodeschema',
            name='wf_schema_family_active_idx',
        ),
        migrations.RemoveField(
            model_name='workflownodeschema',
            name='node_family',
        ),
        migrations.RemoveField(
            model_name='workflownodeschema',
            name='stage_type',
        ),
        migrations.RemoveField(
            model_name='workflownodeschema',
            name='workflow_node_type',
        ),
        migrations.AddIndex(
            model_name='workflownodeschema',
            index=models.Index(fields=['is_active'], name='wf_schema_active_idx'),
        ),
    ]
