services:

  mysql:
    image: mysql:8.2
    restart: unless-stopped
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-aistory_4087}
      - MYSQL_DATABASE=${MYSQL_DB_NAME:-ai_story}
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:latest
    restart: unless-stopped


  backend:
    image: ai_story-v2:latest
    command: gunicorn --chdir /app/backend config.wsgi:application --bind 0.0.0.0:8010 -k gevent --workers 2 --worker-connections 1000 --timeout 3600
    restart: unless-stopped
    volumes:
      - ./data/backend:/app/backend/data
      - ./storage:/app/storage
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - REDIS_HOST=redis
      - MYSQL_DB_NAME=${MYSQL_DB_NAME:-ai_story}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-aistory_4087}
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
    depends_on:
      - redis
      - mysql

  celery:
    image: ai_story-v2:latest
    working_dir: /app/backend
    command: celery -A config worker -l info -P gevent
    restart: unless-stopped
    volumes:
      - ./data/backend:/app/backend/data
      - ./storage:/app/storage
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - REDIS_HOST=redis
      - MYSQL_DB_NAME=${MYSQL_DB_NAME:-}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-}
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
    depends_on:
      - redis
      - mysql

  frontend:
    image: ai_story_frontend-v2:latest
    restart: unless-stopped
    ports:
      - "3003:3000"
    depends_on:
      - backend
