# Generated by Django 3.2.15 on 2026-03-19 05:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('provider_type', models.CharField(choices=[('llm', 'LLM模型'), ('text2image', '文生图模型'), ('image2video', '图生视频模型'), ('image_edit', '图片编辑模型')], max_length=20, verbose_name='模型作用分类')),
                ('executor_class', models.CharField(blank=True, default='', help_text='执行器的完整类路径，如: core.ai_client.openai_client.OpenAIClient', max_length=255, verbose_name='执行器类')),
                ('api_url', models.URLField(verbose_name='API地址')),
                ('api_key', models.CharField(max_length=512, verbose_name='API密钥')),
                ('model_name', models.CharField(max_length=255, verbose_name='模型名称')),
                ('max_tokens', models.IntegerField(default=2000, verbose_name='最大Token数')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度')),
                ('top_p', models.FloatField(default=1.0, verbose_name='Top P')),
                ('timeout', models.IntegerField(default=60, verbose_name='超时时间(秒)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('priority', models.IntegerField(default=0, help_text='用于负载均衡', verbose_name='优先级/权重')),
                ('rate_limit_rpm', models.IntegerField(default=60, verbose_name='每分钟请求数限制')),
                ('rate_limit_rpd', models.IntegerField(default=1000, verbose_name='每天请求数限制')),
                ('extra_config', models.JSONField(blank=True, default=dict, verbose_name='额外配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模型提供商',
                'verbose_name_plural': '模型提供商',
                'db_table': 'model_providers',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_data', models.JSONField(default=dict, verbose_name='请求数据')),
                ('response_data', models.JSONField(default=dict, verbose_name='响应数据')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='使用Token数')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='延迟(毫秒)')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('project_id', models.UUIDField(blank=True, null=True, verbose_name='项目ID')),
                ('stage_type', models.CharField(blank=True, max_length=20, verbose_name='阶段类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('model_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='models.modelprovider', verbose_name='模型提供商')),
            ],
            options={
                'verbose_name': '模型使用日志',
                'verbose_name_plural': '模型使用日志',
                'db_table': 'model_usage_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='modelprovider',
            index=models.Index(fields=['provider_type', 'is_active', '-priority'], name='model_provi_provide_31fd3a_idx'),
        ),
        migrations.AddIndex(
            model_name='modelusagelog',
            index=models.Index(fields=['model_provider', '-created_at'], name='model_usage_model_p_105ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='modelusagelog',
            index=models.Index(fields=['project_id', 'stage_type'], name='model_usage_project_8209bf_idx'),
        ),
    ]
