# Generated by Django 3.2.15 on 2026-06-11 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prompts', '0003_prompttemplate_client_params_promptdebugsession_draft_client_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptSnippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('content', models.TextField(verbose_name='提示词内容')),
                ('node_type', models.CharField(choices=[('text', '文本节点'), ('image', '图片节点'), ('video', '视频节点'), ('all', '全部节点')], default='all', max_length=20, verbose_name='节点类型')),
                ('apply_mode', models.CharField(choices=[('append', '追加'), ('replace', '替换')], default='append', max_length=20, verbose_name='应用方式')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='分类')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_snippets', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '快捷提示词',
                'verbose_name_plural': '快捷提示词',
                'db_table': 'prompt_snippets',
                'ordering': ['-is_favorite', 'sort_order', '-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promptsnippet',
            index=models.Index(fields=['created_by', 'node_type', 'is_active'], name='prompt_snip_created_788eef_idx'),
        ),
        migrations.AddIndex(
            model_name='promptsnippet',
            index=models.Index(fields=['created_by', 'category', 'is_active'], name='prompt_snip_created_57ab36_idx'),
        ),
    ]
